title: Yutong Zheng # your name (or website title) here
logo: "/images/1589335996924.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. student in Carnegie Mellon University 
  <br><br>
  My main research area is Computer Vision. Topics include 3D Generative Adversarial Nets (GANs), Face Manipulation and Recognition. 
  <br><br>
  <a href="https://www.linkedin.com/in/yutongzh/">LinkedIn Profile</a> 
  <br><br>
  <a href="https://scholar.google.com/citations?user=SDTh1I4AAAAJ&hl=en">Google Scholar Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
